//
//  ___VARIABLE_sceneName___ViewControllerTest.swift
//  Sample
//
//  Created by Tom Baranes on 30/03/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import XCTest
import Reusable
@testable import Sample_iOS

final class ___VARIABLE_sceneName___ViewControllerTests: XCTestCase {

    // MARK: IBOutlet

    private var buttonFetchName: UIButton!
    private var tableView: UITableView!

    // MARK: Properties

    private var viewController: ___VARIABLE_sceneName___ViewController!

    // MARK: Life Cycle

    override func setUp() {
        super.setUp()
        viewController = StoryboardScene.___VARIABLE_sceneName___.initialScene.instantiate()
        configureOutlets()
    }

    override func tearDown() {
        super.tearDown()
    }

    private func configureOutlets() {
        buttonFetchName = viewController.view.findView(forIdentifier: ___VARIABLE_sceneName___Accessibility.button.rawValue) as? UIButton
        let tableViewIdentifier = ___VARIABLE_sceneName___Accessibility.tableView.rawValue
        tableView = viewController.view.findView(forIdentifier: tableViewIdentifier) as? UITableView
    }

    private func launchControllerLifeCycle() {
        let window = UIWindow()
        window.addSubview(viewController.view)
        RunLoop.current.run(until: Date())
    }

}

// MARK: - Injection

extension ___VARIABLE_sceneName___ViewControllerTests {

    func testInject() {
        XCTAssertNoThrow(viewController.inject())
    }

}

// MARK: - Configuration

extension ___VARIABLE_sceneName___ViewControllerTests {

    func testControllerLifeCycle() {
        launchControllerLifeCycle()
    }

    func testDefaultConfiguration() {
        launchControllerLifeCycle()
        XCTAssertFalse(buttonFetchName.allTargets.isEmpty)

        let indexPath = IndexPath(row: 0, section: 0)
        XCTAssertNotNil(tableView.dequeueReusableCell(for: indexPath) as ___VARIABLE_sceneName___TableViewCell)
        XCTAssertEqual(tableView.rowHeight, UITableView.automaticDimension)
        XCTAssertNotNil(tableView.dataSource)
        XCTAssertNotNil(tableView.delegate)
    }

}

// MARK: - Actions

extension ___VARIABLE_sceneName___ViewControllerTests {

    func testFetchNamePressed() {
        buttonFetchName.sendActions(for: .touchUpInside)
    }

}
