//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import Foundation

protocol ___VARIABLE_sceneName___PresenterLogic: AnyObject {
    /// TableView's datasource
    var dataSource: ___VARIABLE_sceneName___TableViewDataSource! { get }
    /// TableView's delegate
    var tableViewDelegate: ___VARIABLE_sceneName___TableViewDelegate! { get }

    /// UIViewController's `viewDidLoad` has been called
    func viewDidLoad()
    /// fetch a new name
    func fetchNewName()
}
