//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import Foundation

/// ___VARIABLE_sceneName___ business logic protocol
protocol ___VARIABLE_sceneName___InteractorLogic {

    /// Interactor initializer
    init(presenter: ___VARIABLE_sceneName___InteractorDelegate)

    /// subscribe to notifications
    func subscribe()
    /// unsubscribe to notifications
    func unsubscribe()

    /// Fetch data
    func fetchNewName()
}
