//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import UIKit

protocol ___VARIABLE_sceneName___ViewDelegate: AnyObject {

    /// Configure default static labels
    /// - Parameter viewModel: ___VARIABLE_sceneName___ViewModel
    func configureDefaultLabels(viewModel: ___VARIABLE_sceneName___ViewModel)

    /// display view model
    /// - Parameter viewModel: `___VARIABLE_sceneName___ViewModel`
    func reloadNames(viewModel: ___VARIABLE_sceneName___ViewModel)

}
