//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import UIKit

/// ___VARIABLE_sceneName___ routing logic protocol
protocol ___VARIABLE_sceneName___RouterLogic: AnyObject {

    /// Push VC
    /// - Parameter animated: Bool
    func pushVC(animated: Bool)
}
