//
//  ___VARIABLE_sceneName___TableViewDataSourceDelegate.swift
//  Sample
//
//  Created by Tom Baranes on 30/03/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation

protocol ___VARIABLE_sceneName___TableViewDataSourceDelegate: AnyObject {
    var names: [String] { get }
    var cellDelegate: ___VARIABLE_sceneName___TableViewCellDelegate { get }
}
