//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import XCTest
@testable import ___VARIABLE_sceneName___

final class ___VARIABLE_sceneName___ModelsViewModelTests: XCTestCase {

    // MARK: Properties

    private var viewModel = ___VARIABLE_sceneName___ViewModel()

    // MARK: Life Cycle

    override func setUp() {
        super.setUp()
        viewModel = ___VARIABLE_sceneName___ViewModel()
    }

    override class func tearDown() {
        super.tearDown()
    }

}

// MARK: - Initialization

extension ___VARIABLE_sceneName___ModelsViewModelTests {

    func testIsLoading() {
        XCTAssertFalse(viewModel.isLoading)
        viewModel.isLoading = true
        XCTAssertTrue(viewModel.isLoading)
    }

    func testNames() {
        let names = ["name", "name2"]
        XCTAssertEqual(viewModel.names, [])
        viewModel.names = names
        XCTAssertEqual(viewModel.names, names)
    }

}

// MARK: - Localizables

extension ___VARIABLE_sceneName___ModelsViewModelTests {

    func testLocalizables() {
        XCTAssertEqual(viewModel.navigationBarTitle, "L10n.___VARIABLE_sceneName___.NavigationBar.title")
        XCTAssertEqual(viewModel.fetchNameButton, "Fetch name")
    }

}
