//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import UIKit

struct ___VARIABLE_sceneName___SceneBuilder {

    var scene: UIViewController {
        let viewController = StoryboardScene.___VARIABLE_sceneName___.initialScene.instantiate()
        let presenter = ___VARIABLE_sceneName___Presenter(view: viewController)
        (presenter.router as? ___VARIABLE_sceneName___Router)?.viewController = viewController
        viewController.inject(presenter: presenter)
        return viewController
    }
}
