//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation

public typealias ___VARIABLE_sceneName___Equatable = Character
public typealias ___VARIABLE_sceneName___ = ___VARIABLE_sceneName___Model<___VARIABLE_sceneName___Equatable>

/// a data class to encode/decode a json:
/// - conforms to `Codable` protocols
/// - follow a conditional conformance to equality by `Conformance`
public struct ___VARIABLE_sceneName___Model<Conformance>: Codable {

    // MARK: Properties

    /// the ___VARIABLE_sceneName___'s id
    public let id: String
    /// the ___VARIABLE_sceneName___'s link
    public let link: URL?
    /// the ___VARIABLE_sceneName___'s strings
    public let strings: [String]

    // MARK: Initializers

    public init(id: String,
                link: String,
                strings: [String]) {
        self.id = id
        self.link = URL(string: link)
        self.strings = strings
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id      = try container.decode(String.self, forKey: .id)
        link    = try container.decode(URL.self, forKey: .link)
        strings = try container.decode([String].self, forKey: .strings)
    }

}

// MARK: - CodingKeys

extension ___VARIABLE_sceneName___Model {

    /// coding keys enum as `String`, conforms to `CodingKey` protocol
    private enum CodingKeys: String, CodingKey {
        case id
        case link = "new_link_key"
        case strings
    }

}

// MARK: - Equatable

extension ___VARIABLE_sceneName___Model: Equatable where Conformance: Equatable { }
