//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import Foundation
@testable import ___VARIABLE_sceneName___

final class Mock___VARIABLE_sceneName___ViewDelegate {

    // MARK: Properties

    private(set) var didConfigureDefaultLabels = false
    private(set) var namesReloaded = [String]()
}

// MARK: - ___VARIABLE_sceneName___ViewDelegate

extension Mock___VARIABLE_sceneName___ViewDelegate: ___VARIABLE_sceneName___ViewDelegate {

    func configureDefaultLabels(viewModel: ___VARIABLE_sceneName___ViewModel) {
        didConfigureDefaultLabels = true
    }

    func reloadNames(viewModel: ___VARIABLE_sceneName___ViewModel) {
        namesReloaded = viewModel.names
    }

}
