//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import Foundation

/// view model
struct ___VARIABLE_sceneName___ViewModel {

    // MARK: Localizables

    #warning("use L10n instead of hardcoding string")
    let navigationBarTitle = "L10n.___VARIABLE_sceneName___.NavigationBar.title"
    let fetchNameButton = "Fetch name"

    // MARK: Properties

    var isLoading = false
    var names = [String]()

    // MARK: Life Cycle

    init() {

    }

}
