//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import XCTest
@testable import ___PROJECTNAME___

final class ___VARIABLE_sceneName___Tests: XCTestCase {

    // MARK: Life Cycle

    override func setUp() {
        super.setUp()
    }

    override func tearDown() {
        super.tearDown()
    }

}

// MARK: - Initializer

extension ___VARIABLE_sceneName___Tests {

    func testInitialize___VARIABLE_sceneName___() {
        let model = ___VARIABLE_sceneName___(id: "5",
                                              link: "https://www.apple.com",
                                              strings: ["", "", ""])
        XCTAssertEqual(model.id, "5")
        XCTAssertEqual(model.link?.absoluteString, "https://www.apple.com")
        XCTAssertEqual(model.strings, ["", "", ""])
    }

}
