//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation

protocol ___VARIABLE_sceneName___TableViewDataSourceDelegate: AnyObject {
    var names: [String] { get }
    var cellDelegate: ___VARIABLE_sceneName___TableViewCellDelegate { get }
}
