//
//  Mock___VARIABLE_sceneName___CellDelegate.swift
//  Sample
//
//  Created by Tom Baranes on 30/03/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import Foundation
@testable import Sample_iOS

final class Mock___VARIABLE_sceneName___TableViewCellDelegate {

    // MARK: Properties

    private(set) var didExecuteButton = false

}

// MARK: - ___VARIABLE_sceneName___CellDelegate

extension Mock___VARIABLE_sceneName___TableViewCellDelegate: ___VARIABLE_sceneName___TableViewCellDelegate {

    func executeButton() {
        didExecuteButton = true
    }

}
