//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import Foundation
@testable import ___VARIABLE_sceneName___

final class Mock___VARIABLE_sceneName___TableViewDataSourceDelegate {

    // MARK: Properties

    // swiftlint:disable:next weak_delegate
    private(set) var cellDelegate: ___VARIABLE_sceneName___TableViewCellDelegate = Mock___VARIABLE_sceneName___TableViewCellDelegate()

    // MARK: Life Cycle

    init() {

    }

}

// MARK: - ___VARIABLE_sceneName___TableViewDataSourceDelegate

extension Mock___VARIABLE_sceneName___TableViewDataSourceDelegate: ___VARIABLE_sceneName___TableViewDataSourceDelegate {

    var names: [String] {
        ["test", "test2"]
    }

}
