//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import XCTest
import SwiftyUtils
@testable import ___VARIABLE_sceneName___

final class ___VARIABLE_sceneName___RouterTests: XCTestCase {

    // MARK: Properties

    private var router: ___VARIABLE_sceneName___Router!
    private var viewController: ___VARIABLE_sceneName___ViewController!

    // MARK: Life Cycle

    override func setUp() {
        super.setUp()
        viewController = StoryboardScene.___VARIABLE_sceneName___.initialScene.instantiate()
        let presenter = ___VARIABLE_sceneName___Presenter(view: viewController)
        router = ___VARIABLE_sceneName___Router(presenter: presenter)
        router.viewController = viewController
    }

    override func tearDown() {
        super.tearDown()
    }

}

// MARK: - Initialization

extension ___VARIABLE_sceneName___RouterTests {

    func testInitialize_twiceViewController() {

    }

}

// MARK: - Navigation

extension ___VARIABLE_sceneName___RouterTests {

    func testPushVC() {
        let navigationController = UINavigationController(rootViewController: viewController)
        router.pushVC(animated: false)
        XCTAssertEqual(navigationController.viewControllers.count, 2)
    }

}
