//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import Foundation
@testable import ___VARIABLE_sceneName___

final class Mock___VARIABLE_sceneName___InteractorLogic {
    
    // MARK: Properties

    private(set) var didSubscribe = false
    private(set) var didUnsubscribe = false
    private(set) var didFetchNewName = false

    private var presenter: ___VARIABLE_sceneName___InteractorDelegate!

    // MARK: Life Cycle

    convenience init(presenter: ___VARIABLE_sceneName___InteractorDelegate) {
        self.init()
        self.presenter = presenter
    }

}

// MARK: - ___VARIABLE_sceneName___InteractorLogic

extension Mock___VARIABLE_sceneName___InteractorLogic: ___VARIABLE_sceneName___InteractorLogic {

    func subscribe() {
        didSubscribe = true
    }

    func unsubscribe() {
        didUnsubscribe = true
    }

    func fetchName() {
        didFetchNewName = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            self.presenter.didFetch(name: "name")
        }
    }

}
