//
//  ___VARIABLE_sceneName___Accessibility.swift
//  Sample
//
//  Created by Tom Baranes on 30/03/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import Foundation

enum ___VARIABLE_sceneName___Accessibility: String {
    case button
    case tableView
    case titleLabel
}
