//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import UIKit

final class ___VARIABLE_sceneName___TableViewDelegate: NSObject {

    // MARK: Properties

    private weak var delegate: ___VARIABLE_sceneName___TableViewDelegateLogic?

    // MARK: Life Cycle

    init(delegate: ___VARIABLE_sceneName___TableViewDelegateLogic) {
        self.delegate = delegate
    }

}

// MARK: - UITableViewDelegate

extension ___VARIABLE_sceneName___TableViewDelegate: UITableViewDelegate {

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        delegate?.didSelectRow(at: indexPath)
    }

}
