//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import XCTest
@testable import ___VARIABLE_sceneName___

final class ___VARIABLE_sceneName___ViewTests: XCTestCase {

    // MARK: Properties

    private var view: ___VARIABLE_sceneName___View!

    // MARK: Life Cycle

    override func setUp() {
        super.setUp()
        view = ___VARIABLE_sceneName___SceneBuilder().view as? ___VARIABLE_sceneName___View
    }

    override func tearDown() {
        super.tearDown()
    }

}

// MARK: Computed Properties

extension ___VARIABLE_sceneName___ViewTests {

    func testBody() {
        XCTAssertNotNil(view.body)
    }

}
