//
//  Mock___VARIABLE_sceneName___TableViewDelegateLogic.swift
//  Sample
//
//  Created by Tom Baranes on 30/03/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import UIKit
@testable import Sample_iOS

final class Mock___VARIABLE_sceneName___TableViewDelegateLogic {

    // MARK: Properties

    private(set) var selectedIndexPath: IndexPath?

    // MARK: Life Cycle

    init() {

    }

}

// MARK: - ___VARIABLE_sceneName___TableViewDelegateLogic

extension Mock___VARIABLE_sceneName___TableViewDelegateLogic: ___VARIABLE_sceneName___TableViewDelegateLogic {

    func didSelectRow(at indexPath: IndexPath) {
        selectedIndexPath = indexPath
    }

}
