//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import Foundation
@testable import ___VARIABLE_sceneName___

final class Mock___VARIABLE_sceneName___PresenterLogic {

    // MARK: Properties

    private(set) var didViewDidLoad = false
    private(set) var didFetchNewName = false

    // swiftlint:disable weak_delegate
    var dataSource: ___VARIABLE_sceneName___TableViewDataSource! = ___VARIABLE_sceneName___TableViewDataSource(delegate: Mock___VARIABLE_sceneName___TableViewDataSourceDelegate())
    var tableViewDelegate: ___VARIABLE_sceneName___TableViewDelegate! = ___VARIABLE_sceneName___TableViewDelegate(delegate: Mock___VARIABLE_sceneName___TableViewDelegateLogic())
    // swiftlint:enable weak_delegate

}

// MARK: - ___VARIABLE_sceneName___PresenterLogic

extension Mock___VARIABLE_sceneName___PresenterLogic: ___VARIABLE_sceneName___PresenterLogic {

    func viewDidLoad() {
        didViewDidLoad = true
    }

    func fetchNewName() {
        didFetchNewName = true
    }

}
