//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import UIKit
import Reusable

final class ___VARIABLE_sceneName___ViewController: UIViewController {

    // MARK: IBOutlet

    @IBOutlet private weak var buttonFetchName: UIButton! {
        didSet {
            buttonFetchName.accessibilityIdentifier = ___VARIABLE_sceneName___Accessibility.button.rawValue
            buttonFetchName.addTarget(self, action: #selector(fetchNamePressed), for: .touchUpInside)
        }
    }

    @IBOutlet private weak var tableView: UITableView! {
        didSet {
            tableView.accessibilityIdentifier = ___VARIABLE_sceneName___Accessibility.tableView.rawValue
            tableView.rowHeight = UITableView.automaticDimension
            tableView.register(cellType: ___VARIABLE_sceneName___TableViewCell.self)

            tableView.dataSource = presenter.dataSource
            tableView.delegate = presenter.tableViewDelegate
        }
    }

    // MARK: Properties

    private var presenter: ___VARIABLE_sceneName___PresenterLogic!

    // MARK: Life Cycle

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
    }

}

// MARK: - Injection

extension ___VARIABLE_sceneName___ViewController {

    func inject(presenter: ___VARIABLE_sceneName___PresenterLogic) {
        self.presenter = presenter
    }

}

// MARK: - Actions

extension ___VARIABLE_sceneName___ViewController {

    @objc
    private func fetchNamePressed() {
        presenter.fetchNewName()
    }

}

// MARK: - ___VARIABLE_sceneName___ControllerLogic

extension ___VARIABLE_sceneName___ViewController: ___VARIABLE_sceneName___ViewDelegate {

    func configureDefaultLabels(viewModel: ___VARIABLE_sceneName___ViewModel) {
        self.title = viewModel.navigationBarTitle
        buttonFetchName.setTitle(viewModel.fetchNameButton, for: .normal)
    }

    func reloadNames(viewModel: ___VARIABLE_sceneName___ViewModel) {
        tableView.reloadData()
    }

}
