//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import UIKit

final class ___VARIABLE_sceneName___Router: ___VARIABLE_sceneName___RouterLogic {

    // MARK: Properties

    weak var viewController: UIViewController?
    private weak var presenter: ___VARIABLE_sceneName___RouterDelegate?

    // MARK: Life Cycle

    init(presenter: ___VARIABLE_sceneName___RouterDelegate) {
        self.presenter = presenter
    }

}

// MARK: - Navigation

extension ___VARIABLE_sceneName___Router {

    func pushVC(animated: Bool) {
        let vc = UIViewController()
        viewController?.navigationController?.pushViewController(vc, animated: animated)
    }

}
