//
//  ___VARIABLE_sceneName___TableVIewCellDelegate.swift
//  Sample
//
//  Created by Tom Baranes on 30/03/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Atelier Socle Xcode Templates
//

import Foundation

protocol ___VARIABLE_sceneName___TableViewCellDelegate: AnyObject {
    func executeButton()
}
